# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'BTLESwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SnapKit'
  pod 'ReactiveCocoa', '~> 7.0'
  pod 'ReactiveSwift', '~> 3.0'

end
